language: node_js
node_js:
  - '9'
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE ammo_challenge_test;' -U postgres
deploy:
  provider: heroku
  api_key: ${HEROKU_API_KEY}
  app: backend-ammo-challenge
