version: '3'

services: 
  app:
    image: adalbertorsilvajr/backend-ammo-challenge:latest
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=junior
    build: .
    ports:
      - 3001:3001
    depends_on: 
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=junior
      - POSTGRES_USER=postgres 
    restart: always
    ports: 
      - 5433:5432


